print("Hello, World!")
print("My name is Shahriar Tasin")
print("I am building Tasin's AI Lab")
print("")
print("My goals:")
print("- First 100$ online")
print("-1000$ per month")
print("-3000$ per month")
print("")
print("Current phase: Python Fundamentals")